---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  error = FALSE,
  message = FALSE
)
`%>%` <- magrittr::`%>%`
source("R/my_functions.R")
```

# Projeto cana Aryane J. Ferreira (IAC)

## Análise Preliminar

### Carregando o banco de dados
```{r}
dados <-readr::read_rds("data/my_data.rds")
```

### Resumo estatístico rápido
```{r}
dados$data %>% 
  purrr::map(skimr::skim) %>%
  purrr::map_chr(knitr::knit_print, options = list(skimr_include_summary = FALSE)) %>%
  knitr::asis_output()
```

## Análise com desdobramento.

Observe que nessa análise desdobramos as  interações menores que $0,35$. Utilizando regressão para doses e LSD (teste-t), para forma.

```{r}
dados <- dados %>% 
  dplyr::mutate(
    boxplot = purrr::map(data, my_summary, type="boxplot"),
    histograma = purrr::map(data, my_summary,type="histograma"),
    anova = purrr::map(data, my_summary,type="regressao"),
    interacao = purrr::map(data, my_summary,type="interacao"),
    desdobramento = purrr::map(data, my_summary,type="desdobramento")
  )
```

## Gráficos da interação

```{r}
dados$interacao
```




